spring:
  application:
    name: MyPetStore_SpringBoot

  jpa:
    database: mysql

  datasource:
    url:
      jdbc:mysql://localhost:3306/my_pet_store
    username: root
    hikari:
      jdbc-url: jdbc:mysql://localhost:3306/my_pet_store
      username: root


